openapi: 3.0.1
info:
  title: Sunbird Asset Management API(s)
  description: >-
    The Asset Management API allows you to manage asset over the sunbird
    platform.Apis perform operations related to all the _Asset_ on the Sunbird
    Platform. 

    - Each of the endpoints serve a different purpose, so which one to use
    depends on what you want to do

    - The operations include CRUD (Create, Update, Read and Delete) operations
    and other operations such as upload etc. 

    - The URL for Sunbird Asset API(s) is `asset/v1` 

    - [TestCases](https://www.getpostman.com/collections/40dde03073826216533a)
  termsOfService: 'https://github.com/project-sunbird/sunbird-commons/blob/master/LICENSE'
  contact:
    email: info@sunbird.org
  version: "1.0"
servers:
  - url: 'https://staging.sunbirded.org/api'
paths: